### ISSUE TITLE
Import existing Project to ACB

### ISSUE THREAD

**Issue by RajeshAle** [forcedotcom/try-acb-feedback#10]
<!— As a Beta user, we want to understand how you would like to use Anypoint Code Builder for your use cases. This is for general feedback about your experience using the product and giving us your overall impression. -->

**What is your role?** Sr Integration Developer

**What tools do you use today for your use cases?** Anypoint Studio

**How do you see Anypoint Code Builder help you with your day to day work?** Thinking a replacement for Anypoint Studio

**General feedback:** How to Import an existing project which was built in Anypoint studio to ACB ??

**Comment by martin-scovotti** [comment]
Hi @RajeshAle! You can import a mule app doing a drag and drop into the side bar.
In the following link you can get all instructions required: https://docs.mulesoft.com/anypoint-code-builder/upload-a-project
