### ISSUE TITLE
Command palette missing option

### ISSUE THREAD

**Issue by smaquois123** [forcedotcom/try-acb-feedback#14]
When trying to add an example fragment from Exchange, the "MuleSoft: Add fragment dependency from Exchange" is not in the list.  Other Mulesoft: ... are there.  Using chrome Version 109.0.5414.119 (Official Build) (arm64).

**Comment by simoneegeib** [comment]
Hi @smaquois123 , can you please provide a screenshot? Some commands are context sensitive, and I'd like to make sure you have the API itself open and in focus when you open the command palette

**Comment by vchirag-mulesoft** [comment]
This is just a brief email to let you know that this case will be closed today due to inactivity. If this issue reoccurs or has not been resolved, we will be happy to continue working with you. Please re-open the ticket when you are ready to proceed.

Thanks!
