### ISSUE TITLE
Make ACB available on EU Platform

### ISSUE THREAD

**Issue by GauthierPLM** [forcedotcom/try-acb-feedback#16]
ACB is currently only available on the US version of Anypoint, meaning EU customers that would like to test / use it should make a second account on the US version of Anypoint platform.

As prevent user from accessing theirs assets present on EU platform, we are looking for ACB to be available on the EU version of Anypoint to start to adopt it.

**Comment by simoneegeib** [comment]
Thank you for raising this enhancement. We are planning to support EU for the ACB GA

**Comment by simoneegeib** [comment]
Enhancement is on roadmap
