### ISSUE TITLE
Something went wrong while publishing to Exchange. backend.api.spec.project.is.not.valid Go to Output/MuleDXServer view to see more details.

### ISSUE THREAD

**Issue by sasidharreddyc** [forcedotcom/try-acb-feedback#18]
Something went wrong while publishing to Exchange. backend.api.spec.project.is.not.valid Go to Output/MuleDXServer view to see more details.

unable to publish to exchange from code builder

**Comment by simoneegeib** [comment]
Can you please provide more details on the issue? It would be great if you could use the bug teample, and provide screenshots for the issue

**Comment by vchirag-mulesoft** [comment]
This is just a brief email to let you know that this case will be closed today due to inactivity. If this issue reoccurs or has not been resolved, we will be happy to continue working with you. Please re-open the ticket when you are ready to proceed.

Thanks!
