### ISSUE TITLE
New ACB instance should have relevant dependencies fully pre-installed before first usage

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/try-acb-feedback#20]
**Is your feature request related to a problem? Please describe.**
After creating a new instance of ACB the user has to wait for additional dependencies to be installed. Which then enforce a reload of the IDE.

![image](https://user-images.githubusercontent.com/2205451/219330590-c3eb13c0-0872-48d3-b0d0-01afd776d2ae.png)

**Describe what you are ultimately trying to do**
The expectation is that the ACB instance comes with all relevant dependencies fully installed. The current state leaves the impression that not everything is bundled with the instance.

**Comment by vchirag-mulesoft** [comment]
Thank you for reporting this issue. We created a ticket and will include the fix in an upcoming release.
