### ISSUE TITLE
Home directory should be set per default as trusted directory

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/try-acb-feedback#21]
**Is your feature request related to a problem? Please describe.**
Currently the home folder of the user is not set as a trusted directory.

![image](https://user-images.githubusercontent.com/2205451/219332534-d1dc9350-c6bc-426d-a8d6-7fa40ae3702d.png)

**Describe what you are ultimately trying to do**
The home directory should be set per default as trusted directory, so that the user doesn't have to go through not needed dialogs.

**Comment by simoneegeib** [comment]
Thank you for sharing your feature request. An enhancement has been filed and will be reviewed by our team.. We will get back to you if we need additional information.
