### ISSUE TITLE
Used *.mulesoft.com domains are not trusted per default

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/try-acb-feedback#22]
**Is your feature request related to a problem? Please describe.**
MuleSoft domains that are used throughout ACB are not trusted by default (i. e. anypoint.mulesoft.com, docs.mulesoft.com etc).
![image](https://user-images.githubusercontent.com/2205451/219333833-b60a510b-42b8-434e-93e3-dcd086db1908.png)

**Describe what you are ultimately trying to do**
As this is a vendor-controlled environment the expectation is that vender-sites are trusted-by-default, so that users don't have to go through unnecessary hoops.

**Comment by vchirag-mulesoft** [comment]
Hi @muenzpraeger,

Thank you for logging the issue with MuleSoft.

We need to connect to Mulesoft domains to design API, retrieve an asset from the exchange, and deploy the app to ARM.  We connect to Mulesoft domains as we currently have in Studio. We can create a doc to allow/whitelist the list of domains.

Please let us know your thoughts.

**Comment by muenzpraeger** [comment]
The used domains (i. e. wildcarded *.mulesoft.com) should come pre-trusted on an ACB instance.

**Comment by simoneegeib** [comment]
Thank you for sharing your feature request. An enhancement has been filed and will be reviewed by our team.. We will get back to you if we need additional information.
