### ISSUE TITLE
User not automatically signed-in after instance creation

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/try-acb-feedback#23]
**Is your feature request related to a problem? Please describe.**
When creating an instance of ACB the user is not authenticated against Anypoint Platform.

![image](https://user-images.githubusercontent.com/2205451/219336545-02c700d3-4791-4b23-a6bb-4672e1db5011.png)

**Describe what you are ultimately trying to do**
Having the same experience as with Salesforce Code Builder, where I'm automatically logged in.

**Comment by muenzpraeger** [comment]
Similarly user is not signed in after opening an existing ACB instance, session authentication is not preserved.

**Comment by vchirag-mulesoft** [comment]
Thank you for reporting this issue. We created a ticket and will include the fix in an upcoming release

**Comment by muenzpraeger** [comment]
Please include the ticket number. 

Would also be great to understand why this is issue was closed when not implemented (yet).
