### ISSUE TITLE
Inconsistent UX for wizard experience when browsing for files

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/try-acb-feedback#25]
**Is your feature request related to a problem? Please describe.**
The end user experience when using the wizard-style dialogs is inconsistent when it comes to file/folder selection.

![image](https://user-images.githubusercontent.com/2205451/219345209-85bbeb73-0780-443d-9b73-a88ba5c60ff8.png)

**Describe what you are ultimately trying to do**
The expectation is that the end user uses the custom ui for selecting path, but not that there is a "callout" to the native VS Code file selection.

**Comment by vchirag-mulesoft** [comment]
Hi @muenzpraeger 

Thank you for reporting the enhancement.

Firstly I would like to confirm the problem.
- You are expecting another window to select the path instead of the palette. 
Please kindly confirm we understand correctly.

**Comment by muenzpraeger** [comment]
My expectation is that the workflow happens within the same UX context. Which can be either just using the Palette, or within the custom UI. Currently it's mixed.

**Comment by vchirag-mulesoft** [comment]
Hi @muenzpraeger, 

The file picker is provided by the standard vscode API
The ACB is based on vscode, it is a default one. 

Thank you!
