### ISSUE TITLE
Error message "Mule DX API Component was not installed" pops up after opening ACB

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/try-acb-feedback#26]
**Describe the bug**
After opening an existing ACB instance the error message `Mule DX API Component was not installed` is shown.

The Extension Host window shows the following messsage.

```console
2023-02-16 12:50:44.769 [error] TypeError: Cannot read properties of undefined (reading 'id')
	at /opt/code-server/extensions/mulesoftinc.mule-dx-vscode-4.4.2/out/extension.js:299:41
```

Could not find a repro step (yet).

**Comment by vchirag-mulesoft** [comment]
Hi @muenzpraeger, 

Can you please provide a screenshot/recording of the issue? 

Thanks!

**Comment by muenzpraeger** [comment]
I couldn't repro the VSC status message, but could repro the error message. Both are potentially unrelated errors that showed up at the same time.

https://user-images.githubusercontent.com/2205451/221131036-003ee6f0-3bc1-4166-91b1-fbe1aea9af8a.mp4



The error is thrown b/c the `project` is `undefined`.

```javascript
function registerShowDependenciesHandler(context, platformAPI) {
    context.subscriptions.push(vscode.commands.registerCommand(commands_1.Commands.ShowDependencies, (project) => __awaiter(this, void 0, void 0, function* () {
        platformAPI.then(api => {
            api.getDependencies(project.id).then(response => { // <= project is undefined
                console.debug(response);
            });
            projectDependencyProvider.refresh();
        });
    })));
}
```

**Comment by martin-scovotti** [comment]
Hi @muenzpraeger thanks for reporting this issue and provide us feedback. 
An internal issue was created to fix it, in advance this should not affect any of the existing journeys in the product. 
Please let me know if you experience any issue despite of the error message.

**Comment by vchirag-mulesoft** [comment]
Hi @muenzpraeger,

This is just a follow-up to my previous comment. If you confirm, I would like to close out this issue with your permission.

Regards,
MuleSoft Support

**Comment by muenzpraeger** [comment]
This can be closed. Thanks!
