### ISSUE TITLE
No visual indication of canvas loading time / editor tab naming

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/try-acb-feedback#27]
**Is your feature request related to a problem? Please describe.**
The current experience for opening up a mule app definition is confusing.

1. The visual display of the canvas tab is the same as for the XML file (file name/ file path). This leaves (especially for beginners with ACB) the impression that the XML file has been opened twice, and not that this is a canvas.
2. While the canvas shows on first start the standard VS Code loading bar, it is not clear what is happening (i. e. project indexing). So people look for a long time at an empty screen (in below example screencast for full 13s).

https://user-images.githubusercontent.com/2205451/219373887-f94016dd-050a-4afe-99d4-bb8fd330a990.mp4

**What is missing**

- A differentiated editor tab for the canvas, so that it's easier for the end user to identify what they are looking at/have open in ACB.
- A visual indicator that shows clearly that there is a process running for a fresh opened canvas, and the user just has to wait. Similar to the "Empty Canvas" message, but then directly from the start.

**Comment by vchirag-mulesoft** [comment]
Thank you for sharing your feature request. An enhancement has been filed and will be reviewed by our team. We will get back to you if we need additional information.
