### ISSUE TITLE
Auto-completions/code suggestions in ACB s should follow standard VSC/LSP pattern

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/try-acb-feedback#28]
**Describe the bug**
Auto-completions in ACB are missing two elements:
- No suggestion for closing tags like in other markup languages
- Snippet selection visibility is stopping after the first char

**Expected behavior**
The provided functionality should be similar on how users are experiencing it from VSC in general. The attached video shows:

- :08 - How the open `<flow>` tag doesn't get an auto-close suggestion
- :12 - How the list of suggestions is presented after the first char, but then auto-closes when the user adds a second char
- :14 - How a wrong auto-close hint is shown for `</flow>`

The video contains starting at :42 also some examples on how the standard experience is, as examples are HTML and XML auto-completion/suggestion chosen.

**Impact**
Select from 
* Poor Usability

**Frequency**
Select from 
* Always

**Screenshots/Recordings**

https://user-images.githubusercontent.com/2205451/219597689-83f66afe-8e41-4895-9364-d85c0ee08759.mp4

**Comment by simoneegeib** [comment]
Thank you for reporting this issue. A bug as been filed, which will be prioritized for an upcoming release.
