### ISSUE TITLE
"localhost" and "web-IDE-instance URL" conundrum

### ISSUE THREAD

**Issue by saagnikadhikary** [forcedotcom/try-acb-feedback#29]
**What is your role?** --> Developer

**Question:** Will "localhost" and the "web-IDE-instance URL" point to the same implementation logic? If yes, how are they both referring to one and the same thing?

**Comment by vchirag-mulesoft** [comment]
Hello @saagnikadhikary,

Thank you for logging this case with MuleSoft Support. 

In the HTTP config, you define the host as localhost, and once it deploys we have to invoke using the web-IDE-instance URL. 
The localhost is a hostname that refers to the instance where the application is deployed.

Thanks!

**Comment by saagnikadhikary** [comment]
Hi @vchirag-mulesoft , I need more information around this.

1. So, in Anypoint Studio even after deploying I used to invoke my endpoint using localhost, as _**"localhost:8081/image-generation"**_, for instance. But here in ACB, I need to use web-IDE-instance URL after deploying to call my endpoint, is it?
3. Where is the deployment taking place in case of ACB? Is it on AWS ec2 workers or some place elsewhere?

_Would really appreciate a quicker response._

**Comment by simoneegeib** [comment]
I assume this is not about an actual deployment (like deploy to cloud hub), but rather testing the app locally? We bundle a local runtime with ACB, and when you "run" or "debug", then that is where the app is deployed to, so it is internal to your ACB instance.

**Comment by saagnikadhikary** [comment]
Thanks for your response @simoneegeib . Now I get a fair amount of idea behind that enigmatic web-IDE-instance URL.
