### ISSUE TITLE
move the canvas with the touchpad as the mouse

### ISSUE THREAD

**Issue by alexandramartinez** [forcedotcom/try-acb-feedback#30]
**What is your role?**
Developer Advocate at MuleSoft

**What tools do you use today for your use cases?**
Studio

**How do you see Anypoint Code Builder help you with your day to day work?**
I love love love vscode and i hate eclipse :D 

**General feedback:**
In Studio I can move the graphical canvas with the touchpad (i.e., using the two-finger gesture like when scrolling). In ACB this is currently not possible. I can only move it with a mouse-click drag-and-drop.

**Comment by vchirag-mulesoft** [comment]
Hi @alexandramartinez 

Thank you for logging this issue with MuleSoft Support. 

The graphical canvas is not yet functional in the Beta version. The engineering team is working to provide a better version of the palette. 

Regards,
MuleSoft Support
