### ISSUE TITLE
I should already be signed in to anypoint platform when accessing acb online

### ISSUE THREAD

**Issue by alexandramartinez** [forcedotcom/try-acb-feedback#31]
**What is your role?**
Developer Advocate at MuleSoft

**What tools do you use today for your use cases?**
Studio

**General feedback:**
If I'm opening ACB from Anypoint Platform, I should already be logged in from ACB. However, this is not the case. Users have to manually sign in after opening it.

**Comment by vchirag-mulesoft** [comment]
Hi @alexandramartinez 

Thank you for logging this issue with MuleSoft Support. 

It is a known issue and under the team’s radar. It will be sorted in the GA version.

Best Regards,
MuleSoft Support
