### ISSUE TITLE
While running the application throwing error but no error when debugging it

### ISSUE THREAD

**Issue by anuhappy** [forcedotcom/try-acb-feedback#33]
While running a normal application i am getting this error :
![image](https://user-images.githubusercontent.com/2448265/224592438-30eae14d-e16c-4396-87c3-ff625e42ee28.png)

But the same app runs fine when i debug it .

**Comment by simoneegeib** [comment]
Hi @anuhappy , is this the only exception? Can you please copy the full error, and also your flow xml?
When exactly do you get this?

**Comment by anuhappy** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
    xmlns:http="http://www.mulesoft.org/schema/mule/http"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
    http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
    http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">
        <http:listener-config name="Listener" >
            <http:listener-connection host="0.0.0.0" port="8081" />
        </http:listener-config>
        <flow name="HelloWorld" doc:name="Flow" >
            <http:listener path="/Hello" config-ref="Listener" doc:name="Listener" doc:id="atjbqm" />
           <ee:transform doc:name="Transform Message" doc:id="swxtya" >
            <ee:message >
                <ee:set-payload doc:name="Set payload" doc:id="jsdqgs" ><![CDATA[%dw 2.0
        output application/json
        ---
        {
            firstName : "Anurag",
            lastName : "Doe",
        }]]></ee:set-payload>
            </ee:message>
        </ee:transform>
        <logger doc:name="Logger" doc:id="adjkgv" />
        </flow>
        



</mule>

**Comment by anuhappy** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
    xmlns:http="http://www.mulesoft.org/schema/mule/http"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
    http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
    http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">
        <http:listener-config name="Listener" >
            <http:listener-connection host="0.0.0.0" port="8081" />
        </http:listener-config>
        <flow name="HelloWorld" doc:name="Flow" >
            <http:listener path="/Hello" config-ref="Listener" doc:name="Listener" doc:id="atjbqm" />
           <ee:transform doc:name="Transform Message" doc:id="swxtya" >
            <ee:message >
                <ee:set-payload doc:name="Set payload" doc:id="jsdqgs" ><![CDATA[%dw 2.0
        output application/json
        ---
        {
            firstName : "Anurag",
            lastName : "Doe",
        }]]></ee:set-payload>
            </ee:message>
        </ee:transform>
        <logger doc:name="Logger" doc:id="adjkgv" />
        </flow>
</mule>`

**Comment by simoneegeib** [comment]
Hi @anuhappy , are you still seeing this issue?

**Comment by anuhappy** [comment]
No this can be closed
