### ISSUE TITLE
Not able to see option to deploy to cloudhub from ACB

### ISSUE THREAD

**Issue by anuhappy** [forcedotcom/try-acb-feedback#34]
<!— This repo is for feedback on Anypoint Code Builder during open Beta, please limit your issues to those associated with Anypoint Code Builder. Please let us know if you encounter any issues both creating or launching the web IDEs along with issues implementing your use cases.

This is not a mechanism for receiving support under any agreement or SLA. If you require immediate assistance, please use official support channels. -->

**Describe the bug**
I am not able to see the option of deploy to cloudhub in comman pallete.

**To Reproduce**

**Expected behavior**

**Impact**
Select from 
* Crash/Data Loss
* Malfunctioning
* Poor Usability
* Fit & Finish UI
* Other

**Frequency**
Select from 
* Always
* Often
* Sometimes
* Rarely

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.  They really help!

**Please complete the following information:**

* Anypoint Code Builder web IDE URL
* Browser [e.g. chrome, safari]
* Version [e.g. 29] (can be found on Anypoint Code Builder Central page)

**Additional context**

**Comment by anuhappy** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/2448265/225697212-13199cbc-439a-48d4-89fa-2d39bb9e8302.png)

**Comment by ajoardar** [comment]
I am also facing the same issue. Is there any resolution? It was working fine earlier but I start facing the issue after last CloudHub US 1 outage.

**Comment by simoneegeib** [comment]
This should now be fixed, please confirm

**Comment by anuhappy** [comment]
yes working fine now
