### ISSUE TITLE
MuleSoft: Deploy to Cloudhub - option is not available on command Palette

### ISSUE THREAD

**Issue by ajoardar** [forcedotcom/try-acb-feedback#35]
<!— This repo is for feedback on Anypoint Code Builder during open Beta, please limit your issues to those associated with Anypoint Code Builder. Please let us know if you encounter any issues both creating or launching the web IDEs along with issues implementing your use cases.

This is not a mechanism for receiving support under any agreement or SLA. If you require immediate assistance, please use official support channels. -->

**Describe the bug**
I have created a simple application using "Develop an Integration" option from Anypoint Code Builder. The application is running fine from Anypoint Code Builder. But when try to deploy the application to CloudHub, trying to select the option "MuleSoft: Deploy to Cloudhub" on Command Palette, but getting a response as "no matching command".
I am exploring Anypoint Code Builder from my trial account.
**To Reproduce**

1. Click on Develop an Integration option from Anypoint Code Builder 
2. Create a simple application (with HTTP connector and Transformation)
3. Open the Command Palette (ctrl/cmd + shift + P) and type MuleSoft: Deploy to Cloudhub
4. Getting a response - "no matching command"
**Expected behavior**
It should allow deploying the application on CloudHub

**Impact**
Select from 
* Poor Usability

**Frequency**
Select from 
* Always

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.  They really help!

**Please complete the following information:**

* Anypoint Code Builder web IDE URL - https://hyacinth-yu5in0.builder.code.com
* Browser [e.g. chrome, safari] - Chrome
* Version [e.g. 29]  ver 24.1.0

**Additional context**

**Comment by simoneegeib** [comment]
Are you on a windows laptop? We will deploy a fix for cloud hub deployment tomorrow (Monday)

**Comment by ajoardar** [comment]
Hi Simone,
Yes I am on a Windows machine. Thanks for your update.

Thanks and regards
        Ananda

**Comment by ajoardar** [comment]
Thanks @simoneegeib,
This issue gets resolved and I did able to deploy my application to CloudHub from Anypoint Code Builder. Closing the issue. Thanks a lot for the quick resolution and help.
