### ISSUE TITLE
resource endpoint

### ISSUE THREAD

**Issue by ronny-probo** [forcedotcom/try-acb-feedback#38]
The URL to the Web IDE has changed due to an update on ACB side.

When calling using Postman:
POST https://web-IDE-instance/proxy/8081/api/myendpoint
it used to work just fine

I now receive:
**You need to enable JavaScript to run this app.**

Do you have an idea what is wrong?

Has the web-IDE-instance gotten a new format?

**Comment by vchirag-mulesoft** [comment]
Hi @ronny-probo,

Thank you for submitting an issue.

As the URL has changed, we need to reconfigure the cookie values. I would request you to try the steps mentioned in the article.
- https://docs.mulesoft.com/anypoint-code-builder/ping-locally-deployed-app

Please let us know the outcome!

Regards,
Vishal Chirag
MuleSoft Support

**Comment by ronny-probo** [comment]
Great and thank you! This solved the issue.
