### ISSUE TITLE
Creating API Spec fails with generic error message when API Spec already exists

### ISSUE THREAD

**Issue by weesvisje** [forcedotcom/try-acb-feedback#4]
<!— This repo is for feedback on Anypoint Code Builder during open Beta, please limit your issues to those associated with Anypoint Code Builder. Please let us know if you encounter any issues both creating or launching the web IDEs along with issues implementing your use cases.

This is not a mechanism for receiving support under any agreement or SLA. If you require immediate assistance, please use official support channels. -->

**Describe the bug**
I started the tutorial. When I specified I wanted to create the American Flights API I received a "Something went wrong" message. It turned out I already had an American Flights API specification in my Anypoint environment.

**To Reproduce**

1. Make sure you already have an American Flights API spec in your Anypoint environment
2. Tru to create another American Flights API specification
3. See error

**Expected behavior**
Provide an error message stating that this specification already exists.

**Impact**
Select from 
* Poor Usability

**Frequency**
Select from 
* Always

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.  They really help!

**Please complete the following information:**

* Anypoint Code Builder web IDE URL https://trout-tm1vszvmb.builder.code.com/
* Browser [e.g. chrome, safari] Chrome
* Version [e.g. 29] (can be found on Anypoint Code Builder Central page) ?

**Additional context**
![Screenshot 2023-01-31 at 09 33 56](https://user-images.githubusercontent.com/24624585/215709903-bb316004-087e-49e3-810d-9c3d686e58ec.png)

**Comment by marinarv** [comment]
Thanks for reporting this issue. A ticket was created and we will work on improving this experience.
