### ISSUE TITLE
Something went wrong with my instance!!!

### ISSUE THREAD

**Issue by dinglezos-2022** [forcedotcom/try-acb-feedback#43]
This is my instance > https://squirrel-mld0vz.fra.003.anypoint.code-builder.platform.salesforce.com

**Comment by simoneegeib** [comment]
Hi, can you please elaborate what went wrong with your instance? Are you not able to launch it anymore?

**Comment by dinglezos-2022** [comment]
Never mind. I tried a different browser and it worked.

In Firefox though, I get the following error and cannot launch Code Builder anymore:

`
Something went wrong while preparing your web IDE
Something went wrong, you may want to try to launch it later.
You can try to re-launch it later. Or [report an issue](https://github.com/forcedotcom/try-acb-feedback) with instance URL https://squirrel-mld0vz.fra.003.anypoint.code-builder.platform.salesforce.com`
