### ISSUE TITLE
Name of Exchange asset not showing when !include-ing in editor

### ISSUE THREAD

**Issue by weesvisje** [forcedotcom/try-acb-feedback#5]
<!— This repo is for feedback on Anypoint Code Builder during open Beta, please limit your issues to those associated with Anypoint Code Builder. Please let us know if you encounter any issues both creating or launching the web IDEs along with issues implementing your use cases.

This is not a mechanism for receiving support under any agreement or SLA. If you require immediate assistance, please use official support channels. -->

**Describe the bug**
When including an imported asset from Exchange, you only see an identifier, not the name of the asset

**To Reproduce**

1. type !include
2. press ctrl space
3. select Exchange Modules
4. press ctrl space
5. you only see an identifier (see screen shot)

**Expected behavior**
See a list of named imported Exchange assets

**Impact**
Select from 
* Poor Usability

**Frequency**
Select from 
* Always

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.  They really help!
![Screenshot 2023-01-31 at 09 57 55](https://user-images.githubusercontent.com/24624585/215716009-67ac872a-108e-44ac-94b6-80d1974f6725.png)

**Please complete the following information:**

* Anypoint Code Builder web IDE URL https://trout-tm1vszvmb.builder.code.com/
* Browser [e.g. chrome, safari] Chrome
* Version [e.g. 29] (can be found on Anypoint Code Builder Central page) ?

**Additional context**

**Comment by marinarv** [comment]
Hello @weesvisje. Currently this is a default behaviour on the API Editor. The path to the dependency is built with the GAV, because that is how is stored in the `exchange_modules` folder. The `!include` should point to the exact path where the dependency is stored. We can't do much here it is working as expected.

**Comment by simoneegeib** [comment]
Closing this issue as it is working as expected. Please open a new issue if you have further questions

**Comment by simoneegeib** [comment]
Closing this issue as it is working as expected. Please open a new issue if you have further questions
