### ISSUE TITLE
Windows - Desktop IDE / VSCode extension - Can't authenticate git push

### ISSUE THREAD

**Issue by s0up2up** [forcedotcom/try-acb-feedback#51]
**Describe the bug**
- Attempting to push changes implemented via VS Code extension (RAML spec changes) to Design Center. 
- Signed in via ACB (See screenshot1)
- Try and sync changes (git push) to remote origin (being anypoint git repo), and get prompted to sign into Git Credential Manager
- Enter Anypoint credentials in (see Screenshot 2)
- git remote sends back a 401 Unauthorised message (see Screenshot 3)

**To Reproduce**

1. Load VS Code and Open MuleSoft Anypoint Code Builder extension (see Screenshot 4)
2. Click "Design an API" and enter Project details
3. Make changes to a RAML file
4. Commit changes via Source Control panel (or git CLI) then sync changes (git push)
5. Get prompted for credentials via Windows Git Credentials Manager, and enter them in
6. Git output shows a failed authentication message

**Expected behavior**
Be able to push stagged commits to Anypoint platform.

**Impact**
Crash/Data Loss - Unable to deploy changes (i.e., RAML changes) to Anypoint platform.

**Frequency**
Always

**Screenshots/Recordings**
- Screenshot 1: ![image](https://github.com/forcedotcom/try-acb-feedback/assets/20691614/a55fe505-d129-4a8b-b93a-2c7ec2c5d4da)
- Screenshot 2: 
![image](https://github.com/forcedotcom/try-acb-feedback/assets/20691614/d442a5d0-9cc8-4d36-9544-e105b10aff8e)
- Screenshot 3: 
![image](https://github.com/forcedotcom/try-acb-feedback/assets/20691614/be945ad4-777e-4305-8273-1832a6fba4c9)
- Screenshot 4: 
![image](https://github.com/forcedotcom/try-acb-feedback/assets/20691614/c552c70f-0f34-4348-9705-6be405defc70)

**Please complete the following information:**
* Application - Anypoint Code Builder desktop IDE
* Browser [e.g. chrome, safari] - N/A
* Version [e.g. 29] (can be found on Anypoint Code Builder Central page) - v4.2.0

**Additional context**

**Comment by jimdandrews** [comment]
I had the same problem with as Brendan. I even tried to redirect my Design Center to my own GitHub repo and use those credentials but that didn't work either.  I'm wondering if it's a token thing and we need to use connected apps or something.  but it pulls down existing designs just fine.

Also, if i create a new Design project from within ACB, it gets created in Design Center (an initial version) but then any changes i make i can't push (for the same reason as above).  but that initial creation doesn't ask fro credentials.

**Comment by SantiSuarezMS** [comment]
Hi @s0up2up !! We had a similar issue reported where an attempt to push will fail on the first attempt with a`401` but subsequent tries would go through (as long as you're already logged in to Anypoint).
Could you please try this and let me know if you can push?

1. Load VS Code and Open MuleSoft Anypoint Code Builder extension
2. Click "Design an API" and enter Project details (log in to Anypoint if prompted)
3. Make changes to a RAML file
4. Commit changes via Source Control panel (or git CLI) then sync changes (git push)
5. Get prompted for credentials via Windows Git Credentials Manager, ignore and close Git Credential Manager
6. Git output shows a failed authentication message
7. Attempt to push changes again

Let me know if this allows you to push your changes, this is not only a workaround, but also I want to check if it is related to an internal bug we already addressed.

Thanks in advance!

cc @simoneegeib

**Comment by simoneegeib** [comment]
Also, which OS are you on?

**Comment by s0up2up** [comment]
@SantiSuarezMS - looks like that worked, ignoring the Git Cred Mgr prompt seems to allow it to push the changes as I would expect.

![image](https://github.com/forcedotcom/try-acb-feedback/assets/20691614/b0313569-b1de-471f-b2ea-aeebfee1cf0d)

Saying that, the source control panel in VSCode didn't track the changes, it had to be actioned via the Git CLI manually.

@simoneegeib - Fully patched Windows 11 Enterprise (v 10.0.22000 Build 22000, managed via Intune policies (so no local Admin privileges)), w/ the following versioning on VS Code:
![image](https://github.com/forcedotcom/try-acb-feedback/assets/20691614/87356036-87e7-42d7-b1de-b4b1198d4fa8)

**Comment by simoneegeib** [comment]
Thanks for getting back to us. This issue has now been fixed and will be available in the new release next month
