### ISSUE TITLE
Anypoint Code builder seemingly not installing/running properly

### ISSUE THREAD

**Issue by brandon21486** [forcedotcom/try-acb-feedback#52]
**Describe the bug**
I have installed all the extensions for Anypoint Code Builder but it never seems to run correctly and when opening I get a popup saying Mule Platform proces finished. Please, restart. When I try to open the "Design an API" quick action I get a message saying "Mule DX API Component was not installed" despite having all of the extensions installed. I have installed on a user level as well as Administrator and it is just not working.

**To Reproduce**

*This seems to be related to my set up obviously*
1. Install VS Code
2. Install Extension pack
3. Restart
5. Try to Design an API
6. See error

**Expected behavior**
Expect this to install and work

**Impact**
Select from 
* Crash/Data Loss

**Frequency**
Select from 
* Always

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.  They really help!
![Mulesoft_ACB_platform_proc_fin](https://github.com/forcedotcom/try-acb-feedback/assets/18442227/32f252cc-97ee-40d1-899c-b801afad5446)
![Mulesoft_ACB_dx_not_installed](https://github.com/forcedotcom/try-acb-feedback/assets/18442227/4ea456d6-80b6-4e14-8ffb-ff4c5beee43c)
![Mulesoft_ACB_Extensions](https://github.com/forcedotcom/try-acb-feedback/assets/18442227/20b62ef3-22f2-4d60-a8c3-12047f1fd8f6)
![VSCodeVersion](https://github.com/forcedotcom/try-acb-feedback/assets/18442227/efd2fc37-75f4-4cac-b048-7ade6d0d7177)

**Please complete the following information:**

* Anypoint Code Builder web IDE URL
* Browser [e.g. chrome, safari]
* Version [e.g. 29] (can be found on Anypoint Code Builder Central page)

**Additional context**
I am trying to be prepared for release as this tool seems much more user friendly than Studio

**Comment by brandon21486** [comment]
Appears something was corrupted on install. Had to uninstall and delete everything in extensions and vs code settings and reinstall.

**Comment by alexandramartinez** [comment]
fyi for those who are still getting here. i made this guide to remove the extension and its cache to start from scratch. it's been helping other muleys get rid of the `Mule Platform process finished. Please, restart.` error

https://dev.to/devalexmartinez/troubleshooting-acb-installation-issues-463m
