### ISSUE TITLE
Tutorial documentation wrong: File > Preferences > User Snippets should be File > Preferences > Configure User Snippets

### ISSUE THREAD

**Issue by weesvisje** [forcedotcom/try-acb-feedback#6]
<!— This repo is for feedback on Anypoint Code Builder during open Beta, please limit your issues to those associated with Anypoint Code Builder. Please let us know if you encounter any issues both creating or launching the web IDEs along with issues implementing your use cases.

This is not a mechanism for receiving support under any agreement or SLA. If you require immediate assistance, please use official support channels. -->

**Describe the bug**
Tutorial documentation wrong: File > Preferences > User Snippets should be File > Preferences > Configure User Snippets

**To Reproduce**

1. Go to https://docs.mulesoft.com/anypoint-code-builder/create-xml-snippets
2. See error

**Expected behavior**
Tutorial should say: File > Preferences > Configure User Snippets

**Impact**
Select from 
* Other

**Frequency**
Select from 
* Always

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.  They really help!
![Screenshot 2023-01-31 at 10 43 08](https://user-images.githubusercontent.com/24624585/215725471-9a1cf063-898d-4b4d-a017-bfbfedba43b8.png)

**Please complete the following information:**

* Anypoint Code Builder web IDE URL
* Browser [e.g. chrome, safari]
* Version [e.g. 29] (can be found on Anypoint Code Builder Central page)

**Additional context**

**Comment by simoneegeib** [comment]
@fermujica

**Comment by fermujica** [comment]
Thanks for reporting @weesvisje 

The screenshot and UI label in the documentation was updated.
