### ISSUE TITLE
Tutorial documentation wrong: Make a GET request to http://localhost:8081/flights.

### ISSUE THREAD

**Issue by weesvisje** [forcedotcom/try-acb-feedback#7]
<!— This repo is for feedback on Anypoint Code Builder during open Beta, please limit your issues to those associated with Anypoint Code Builder. Please let us know if you encounter any issues both creating or launching the web IDEs along with issues implementing your use cases.

This is not a mechanism for receiving support under any agreement or SLA. If you require immediate assistance, please use official support channels. -->

**Describe the bug**
The tutorial documentation in the section https://docs.mulesoft.com/anypoint-code-builder/use-dataweave-to-transform-data says: "Make a GET request to http://localhost:8081/flights."

**To Reproduce**

1. Go to step 8 of https://docs.mulesoft.com/anypoint-code-builder/use-dataweave-to-transform-data 
2. See error

**Expected behavior**
Should be: make a GET request to https://<web-IDE-instance>/api/8081/flights.

**Impact**
Select from 
* Other

**Frequency**
Select from 
* Always

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.  They really help!
![Screenshot 2023-01-31 at 12 09 10](https://user-images.githubusercontent.com/24624585/215744926-391f4e72-d141-431d-9ab4-6c78aeaaac4f.png)

**Please complete the following information:**

* Anypoint Code Builder web IDE URL
* Browser [e.g. chrome, safari]
* Version [e.g. 29] (can be found on Anypoint Code Builder Central page)

**Additional context**

**Comment by simoneegeib** [comment]
@fermujica

**Comment by fermujica** [comment]
Thank you @weesvisje 
I'm revisiting this example. It's possible that the instructions are outdated.

**Comment by fermujica** [comment]
The tutorial had old instructions. Indeed, users should make a GET request to their web IDE instance URL (plus `/proxy/8081/flights`) as in previous steps.

Thanks for flagging this instance. It was addressed and it will get published automatically in a few more hours.
https://github.com/mulesoft/docs-code-builder/pull/25
