### ISSUE TITLE
Web page will not load

### ISSUE THREAD

**Issue by deanskibum** [forcedotcom/try-acb-feedback#8]
<!— This repo is for feedback on Anypoint Code Builder during open Beta, please limit your issues to those associated with Anypoint Code Builder. Please let us know if you encounter any issues both creating or launching the web IDEs along with issues implementing your use cases.

This is not a mechanism for receiving support under any agreement or SLA. If you require immediate assistance, please use official support channels. -->

**Describe the bug**
When opening web IDE
An unexpected error occurred that requires a reload of this page. The workbench failed to connect to the server (Error: WebSocket close with status code 1006)

**To Reproduce**

1. Click on 'Launch Web IDE .'
2. See error (above)

**Expected behavior**

**Impact**
Select from 
* Crash/Data Loss

**Frequency**
Select from 
* Always

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.  They really help!

**Please complete the following information:**

* Anypoint Code Builder web IDE URL
* Browser chrome
* Version 23.9.3

**Additional context**

**Comment by simoneegeib** [comment]
Hi! Was the web IDE created successfully? If yes, please share the URL

**Comment by vchirag-mulesoft** [comment]
This is just a brief email to let you know that this issue will be closed today due to inactivity. If this issue reoccurs or has not been resolved, we will be happy to continue working with you. Please re-open the ticket when you are ready to proceed.

Thanks!
