### ISSUE TITLE
Unable to Create Project to Design an API

### ISSUE THREAD

**Issue by RyanGrondalMuleSoft** [forcedotcom/try-acb-feedback#9]
**Describe the bug**
Unable to 'Design an API'. Fails when creating the project.

**To Reproduce**
- Click on Design an API
- In the 'Desing an API' popup, enter: 'American Flights API' for Project Name, '/home/Ryan_Grondal_MuleSoft' for Project Location, 'RAML 1.0' for API Specification Language.
- Click 'Create Project'

**Expected behavior**
Project to be created.

**Impact**
- Malfunctioning

**Frequency**
-  Always

**Screenshots/Recordings**
- Error is "Something went wrong when creating project American Flights API. Go to Output/MuleDXServer view to see more details."

**Please complete the following information:**

* Anypoint Code Builder web IDE URL = https://plano-vufiq3lbt.builder.code.com/
* Browser [e.g. chrome, safari] = Chrome

<img width="1422" alt="CaptureCodeBuilder" src="https://user-images.githubusercontent.com/38930603/215922368-d44abad1-ad9f-4fb2-94d4-3e7e0d945e86.PNG">

**Comment by simoneegeib** [comment]
Please also check if you already have an API with the same name in Design Center. But as Marina said, checking the output would help identifying the issue

**Comment by RyanGrondalMuleSoft** [comment]
Thanks - it turns out that I had an 'American Flights API' spec already defined many years ago ;) 

I tried a different project name and it created the project for me. thanks :)

**Comment by simoneegeib** [comment]
Great, closing this issue
